// Phase 9M — architecture summary for Agent context: the module dependency graph (Phase 9L) as a
// Mermaid diagram plus the ranked module list from that graph and the most depended-on files from
// the code map (Phase 9I/9K). Everything is computed by Rust and rendered here from metadata only —
// no file contents, no new native command, no diagram is ever written into the repository. The
// "diagram" is emitted as text so it stays inside the same context budget and needs no charting
// dependency.

import { buildCodeMap, type CodeMap } from "./codeMap";
import { buildCodeGraph, type CodeGraph } from "./codeGraph";

export const ARCHITECTURE_CONTEXT_PATH = "devlab-architecture.md";

export interface ArchitectureSnapshot {
  graph: CodeGraph;
  /** The exported-only code map, or null when the map build failed (the graph still stands alone). */
  map: CodeMap | null;
}

const MAX_DIAGRAM_NODES = 24;
const MAX_DIAGRAM_EDGES = 60;
const MAX_LIST_MODULES = 12;
const MAX_TOP_FILES = 8;
const MAX_EXTERNAL_MODULES = 6;
const MIN_RENDER_CHARS = 1_024;

export async function buildArchitectureSnapshot(): Promise<ArchitectureSnapshot> {
  const [graph, map] = await Promise.all([
    buildCodeGraph(),
    buildCodeMap({ exportedOnly: true }).catch(() => null),
  ]);
  return { graph, map };
}

export function describeArchitecture(snapshot: ArchitectureSnapshot): string {
  const { graph, map } = snapshot;
  const parts = [
    `${graph.moduleCount} module${graph.moduleCount === 1 ? "" : "s"}`,
    `${graph.internalEdges} edge${graph.internalEdges === 1 ? "" : "s"}`,
  ];
  if (map) parts.push(`${map.fileCount} mapped file${map.fileCount === 1 ? "" : "s"}`);
  parts.push(`${graph.buildMs + (map?.buildMs ?? 0)} ms`);
  if (graph.truncated) parts.push(`graph truncated (${graph.truncationReason ?? "budget"})`);
  return parts.join(" · ");
}

export interface RenderedArchitecture {
  markdown: string;
  diagramNodes: number;
  diagramEdges: number;
  listedModules: number;
  clipped: boolean;
}

/**
 * Renders a Mermaid module diagram plus ranked module/file lists within `maxChars`. Whole blocks and
 * whole lines are dropped from the end until the budget fits, so the model never sees a half diagram
 * or a dangling bullet.
 */
export function renderArchitecture(snapshot: ArchitectureSnapshot, maxChars: number): RenderedArchitecture {
  const { graph, map } = snapshot;
  const budget = Math.max(MIN_RENDER_CHARS, Math.floor(maxChars));
  const header = [
    "# Workspace architecture",
    "Generated by DevLab from the native dependency graph and code map (metadata only; no file contents).",
    architectureCounts(snapshot),
    "The diagram is Mermaid text (module \u2192 module, edge label = number of file-level imports). Modules are ordered by summed importance.",
  ];
  if (graph.truncated) header.push(`Note: the graph build stopped early (${graph.truncationReason ?? "budget"}); later modules are missing.`);
  if (!map) header.push("Note: the companion code map could not be built, so per-file rankings are omitted.");
  header.push("");

  const atoms = architectureAtoms(graph, map);
  const wantedModules = Math.min(MAX_LIST_MODULES, graph.moduleCount);
  let kept = selectAtoms(atoms, header.join("\n").length + 1, budget);
  let notes = collectNotes(graph, kept, atoms, wantedModules);
  let markdown = joinArchitecture(header, kept, notes);
  // The footer is sized from the notes, so a long note can push the result over; drop whole atoms
  // (never lines) until it fits.
  while (markdown.length > budget && kept.length > 0) {
    kept = kept.slice(0, kept.length - 1);
    notes = collectNotes(graph, kept, atoms, wantedModules);
    markdown = joinArchitecture(header, kept, notes);
  }
  return {
    markdown,
    diagramNodes: kept.some((atom) => atom.kind === "diagram") ? atoms.diagramNodes : 0,
    diagramEdges: kept.some((atom) => atom.kind === "diagram") ? atoms.diagramEdges : 0,
    listedModules: kept.filter((atom) => atom.kind === "module").length,
    clipped: notes.length > 0 || graph.truncated,
  };
}

interface ArchitectureAtom {
  kind: "diagram" | "modules-heading" | "module" | "modules-tail" | "files" | "external";
  lines: string[];
}

type ArchitectureAtoms = ArchitectureAtom[] & { diagramNodes: number; diagramEdges: number };

/** Splits the summary into atoms: blocks that must stay whole (diagram, trailing lists) and single
 *  module bullets that may be dropped individually. */
function architectureAtoms(graph: CodeGraph, map: CodeMap | null): ArchitectureAtoms {
  const diagram = renderDiagram(graph);
  const atoms: ArchitectureAtom[] = [];
  if (diagram.lines.length > 0) {
    atoms.push({ kind: "diagram", lines: diagram.lines });
  }
  const moduleLines = renderModules(graph);
  if (moduleLines.length > 0) {
    atoms.push({ kind: "modules-heading", lines: [moduleLines[0], ""] });
    for (const line of moduleLines.slice(1)) {
      atoms.push({
        kind: line.startsWith("- **") ? "module" : "modules-tail",
        lines: [line],
      });
    }
  }
  const fileLines = map ? renderTopFiles(map) : [];
  if (fileLines.length > 0) {
    atoms.push({ kind: "files", lines: fileLines });
  }
  const externalLines = renderExternal(graph);
  if (externalLines.length > 0) {
    atoms.push({ kind: "external", lines: externalLines });
  }
  const result = atoms as ArchitectureAtoms;
  result.diagramNodes = diagram.nodes;
  result.diagramEdges = diagram.edges;
  return result;
}

function selectAtoms(atoms: ArchitectureAtoms, usedStart: number, budget: number): ArchitectureAtom[] {
  let used = usedStart;
  const kept: ArchitectureAtom[] = [];
  for (const atom of atoms) {
    const size = atom.lines.join("\n").length + 2;
    if (used + size > budget) {
      continue;
    }
    used += size;
    kept.push(atom);
  }
  if (!kept.some((atom) => atom.kind === "module")) {
    // A heading with no bullet is noise.
    return kept.filter((atom) => atom.kind !== "modules-heading" && atom.kind !== "modules-tail");
  }
  return kept;
}

function collectNotes(graph: CodeGraph, kept: ArchitectureAtom[], atoms: ArchitectureAtoms, wantedModules: number): string[] {
  const notes: string[] = [];
  const has = (kind: string) => kept.some((atom) => atom.kind === kind);
  const offered = (kind: string) => atoms.some((atom) => atom.kind === kind);
  if (offered("diagram") && !has("diagram")) notes.push("the Mermaid diagram was dropped to fit the budget");
  const listed = kept.filter((atom) => atom.kind === "module").length;
  if (listed < wantedModules) {
    const missing = wantedModules - listed;
    notes.push(`${missing} lower-ranked module${missing === 1 ? " was" : "s were"} dropped to fit the budget`);
  }
  if ((offered("files") && !has("files")) || (offered("external") && !has("external"))) {
    notes.push("the trailing lists were dropped to fit the budget");
  }
  if (graph.omittedModules > 0 && listed >= wantedModules) {
    notes.push(`${graph.omittedModules} further module${graph.omittedModules === 1 ? "" : "s"} were not returned by the native build`);
  }
  return notes;
}

function joinArchitecture(header: string[], atoms: ArchitectureAtom[], notes: string[]): string {
  const body: string[] = [];
  let previousWasBlock = false;
  for (const atom of atoms) {
    const lines = [...atom.lines];
    while (lines.length > 0 && lines[lines.length - 1] === "") {
      lines.pop();
    }
    if (lines.length === 0) continue;
    const isBlock = atom.kind !== "module";
    if (body.length > 0 && (isBlock || previousWasBlock)) {
      // Bullets stay in one tight list; blocks and headings are separated.
      body.push("");
    }
    body.push(...lines);
    previousWasBlock = isBlock;
  }
  const footer: string[] = [];
  if (notes.length > 0) {
    if (body.length > 0) footer.push("");
    footer.push(`\u2026 ${notes.join(" and ")}. Attach the dependency graph on its own, or narrow the workspace, for the full picture.`);
  }
  return [...header, ...body, ...footer].join("\n").trimEnd();
}

function architectureCounts(snapshot: ArchitectureSnapshot): string {
  const { graph, map } = snapshot;
  const parts = [
    `${graph.moduleCount} modules from ${graph.fileCount} files`,
    `${graph.internalEdges} in-repo import edges`,
    `${graph.externalReferences} external references`,
    `${graph.leafModules} stand-alone module${graph.leafModules === 1 ? "" : "s"}`,
  ];
  if (map) parts.push(`${map.symbolCount} exported symbols`);
  return parts.join(" · ");
}

function renderDiagram(graph: CodeGraph): { lines: string[]; nodes: number; edges: number } {
  const ranked = graph.modules.slice(0, MAX_DIAGRAM_NODES);
  const ids = new Map<string, string>();
  ranked.forEach((module, index) => {
    ids.set(module.module, `m${index}`);
  });
  const edges: Array<{ from: string; to: string; weight: number }> = [];
  for (const module of graph.modules) {
    const from = ids.get(module.module);
    if (!from) continue;
    for (const edge of module.dependsOn) {
      const to = ids.get(edge.module);
      if (!to) continue;
      edges.push({ from, to, weight: edge.weight });
    }
  }
  edges.sort((left, right) => right.weight - left.weight || left.from.localeCompare(right.from) || left.to.localeCompare(right.to));
  const kept = edges.slice(0, MAX_DIAGRAM_EDGES);
  const connected = new Set<string>();
  for (const edge of kept) {
    connected.add(edge.from);
    connected.add(edge.to);
  }
  const nodes = ranked.filter((module) => connected.has(ids.get(module.module) ?? ""));
  if (nodes.length === 0 || kept.length === 0) {
    return { lines: [], nodes: 0, edges: 0 };
  }
  const lines = ["## Module dependency diagram", "", "```mermaid", "flowchart LR"];
  for (const module of nodes) {
    lines.push(`  ${ids.get(module.module)}["${escapeLabel(module.module)}"]`);
  }
  for (const edge of kept) {
    lines.push(edge.weight > 1 ? `  ${edge.from} -->|${edge.weight}| ${edge.to}` : `  ${edge.from} --> ${edge.to}`);
  }
  lines.push("```", "");
  const hidden = graph.moduleCount - nodes.length;
  if (hidden > 0) {
    lines.push(`Diagram covers ${nodes.length} of ${graph.moduleCount} modules (most important first; ${hidden} omitted).`);
  }
  return { lines, nodes: nodes.length, edges: kept.length };
}

function renderModules(graph: CodeGraph): string[] {
  const lines = ["## Modules by importance", ""];
  for (const module of graph.modules.slice(0, MAX_LIST_MODULES)) {
    const usedBy = module.dependedOnBy.length > 0
      ? `used by ${module.dependedOnBy.map((edge) => `${edge.module} (${edge.weight})`).join(", ")}`
      : "not imported by another module";
    const dependsOn = module.dependsOn.length > 0
      ? `depends on ${module.dependsOn.map((edge) => `${edge.module} (${edge.weight})`).join(", ")}`
      : "no cross-module dependencies";
    lines.push(`- **${module.module}** \u2014 ${module.files} file${module.files === 1 ? "" : "s"} \u00b7 ${module.importance.toFixed(2)}\u00d7 \u00b7 ${dependsOn} \u00b7 ${usedBy}`);
  }
  if (graph.omittedModules > 0) {
    lines.push(`- \u2026 ${graph.omittedModules} further module${graph.omittedModules === 1 ? "" : "s"} were not returned by the native build.`);
  }
  return lines;
}

function renderTopFiles(map: CodeMap): string[] {
  const top = map.rank?.top?.slice(0, MAX_TOP_FILES) ?? [];
  if (top.length === 0) return [];
  const lines = ["## Most depended-on files (exported symbols only)", ""];
  for (const entry of top) {
    lines.push(`- **${entry.path}** — ${entry.importance.toFixed(2)}× · imported by ${entry.inDegree}`);
  }
  return lines;
}

function renderExternal(graph: CodeGraph): string[] {
  const withExternal = graph.modules
    .filter((module) => module.externalSamples.length > 0)
    .slice(0, MAX_EXTERNAL_MODULES);
  if (withExternal.length === 0) return [];
  const lines = ["## External packages outside the workspace", ""];
  for (const module of withExternal) {
    const more = module.externalDeps - module.externalSamples.length;
    lines.push(`- **${module.module}** — ${module.externalSamples.join(", ")}${more > 0 ? ` +${more} more` : ""}`);
  }
  return lines;
}

function escapeLabel(value: string): string {
  return value.replace(/"/g, "'").replace(/[<>{}[\]|]/g, " ");
}
