// Phase 9H — renderer client for native Tree-Sitter code outlines. Rust reads the file inside the
// workspace boundary, parses it with a compiled-in grammar and returns symbol metadata only
// (kind, name, one-line signature, line range). No file contents cross this boundary, nothing is
// cached or written, and unsupported extensions are reported honestly rather than guessed.

import { invoke, isTauri } from "@tauri-apps/api/core";

export interface CodeOutlineLanguage {
  id: string;
  label: string;
  extensions: string[];
}

export interface CodeOutlineLimits {
  maxBytes: number;
  maxSymbols: number;
  maxDepth: number;
  parseDeadlineMs: number;
}

export interface CodeOutlineCatalog {
  languages: CodeOutlineLanguage[];
  limits: CodeOutlineLimits;
}

export type CodeOutlineSymbolKind =
  | "function" | "method" | "class" | "interface" | "type" | "enum" | "namespace" | "module"
  | "struct" | "trait" | "impl" | "constant" | "variable" | "property" | "macro";

export interface CodeOutlineSymbol {
  kind: CodeOutlineSymbolKind | string;
  name: string;
  signature: string;
  startLine: number;
  endLine: number;
  depth: number;
  exported: boolean;
}

export interface CodeOutline {
  path: string;
  supported: boolean;
  language: string | null;
  languageLabel: string | null;
  revision: string;
  size: number;
  modifiedMs: number | null;
  lineCount: number;
  symbolCount: number;
  truncated: boolean;
  hasSyntaxErrors: boolean;
  parseMs: number;
  symbols: CodeOutlineSymbol[];
  note: string;
}

/** Extensions with a compiled-in grammar; mirrors the Rust table so the UI can offer the action only where it works. */
export const OUTLINE_EXTENSIONS = ["ts", "mts", "cts", "tsx", "js", "mjs", "cjs", "jsx", "rs", "py", "pyi", "go"] as const;

export function outlineAdapterAvailable(): boolean {
  return isTauri();
}

export function outlineExtensionOf(path: string): string {
  const name = path.split("/").pop() ?? path;
  const dot = name.lastIndexOf(".");
  if (dot <= 0) return "";
  return name.slice(dot + 1).toLowerCase();
}

export function canOutlinePath(path: string): boolean {
  return (OUTLINE_EXTENSIONS as readonly string[]).includes(outlineExtensionOf(path));
}

export async function codeOutlineLanguages(): Promise<CodeOutlineCatalog> {
  return invoke<CodeOutlineCatalog>("code_outline_languages");
}

export async function codeOutlineFile(relativePath: string): Promise<CodeOutline> {
  return invoke<CodeOutline>("code_outline_file", { relativePath });
}

export function describeCodeOutline(outline: CodeOutline): string {
  if (!outline.supported) return outline.note;
  const parts = [
    `${outline.symbolCount} symbol${outline.symbolCount === 1 ? "" : "s"}`,
    outline.languageLabel ?? outline.language ?? "unknown grammar",
    `${outline.lineCount} lines`,
    `${outline.parseMs} ms`,
  ];
  if (outline.hasSyntaxErrors) parts.push("syntax errors");
  if (outline.truncated) parts.push("truncated");
  return parts.join(" · ");
}

const KIND_ORDER: Record<string, number> = {
  module: 0, namespace: 0, class: 1, struct: 1, interface: 1, trait: 1, enum: 1, impl: 2, type: 3,
  function: 4, method: 4, constant: 5, variable: 6, property: 7, macro: 8,
};

export function sortOutlineSymbols(symbols: CodeOutlineSymbol[], order: "source" | "kind"): CodeOutlineSymbol[] {
  if (order === "source") return symbols;
  return [...symbols].sort((a, b) => (KIND_ORDER[a.kind] ?? 9) - (KIND_ORDER[b.kind] ?? 9) || a.startLine - b.startLine);
}

/**
 * Renders the outline as compact markdown for model context. Only metadata is emitted: names,
 * kinds, one-line signatures and line ranges — never file bodies.
 */
export function renderCodeOutline(outline: CodeOutline): string {
  const lines: string[] = [
    `# Code outline: ${outline.path}`,
    `Generated by DevLab's native Tree-Sitter outline (metadata only; no file contents).`,
    `Language: ${outline.languageLabel ?? outline.language ?? "unsupported"} · ${outline.lineCount} lines · ${outline.size} bytes · revision ${outline.revision.slice(0, 12)}`,
  ];
  if (!outline.supported) {
    lines.push("", outline.note);
    return lines.join("\n");
  }
  if (outline.hasSyntaxErrors) lines.push("Note: the file has syntax errors; this outline may be partial.");
  if (outline.truncated) lines.push(`Note: only the first ${outline.symbolCount} symbols are listed.`);
  lines.push("", "| Lines | Kind | Symbol | Signature |", "|---|---|---|---|");
  for (const symbol of outline.symbols) {
    const indent = "  ".repeat(Math.max(0, symbol.depth));
    const name = `${indent}${symbol.exported ? "**" : ""}${escapeCell(symbol.name)}${symbol.exported ? "**" : ""}`;
    const range = symbol.startLine === symbol.endLine ? `${symbol.startLine}` : `${symbol.startLine}–${symbol.endLine}`;
    lines.push(`| ${range} | ${symbol.kind} | ${name} | \`${escapeCell(symbol.signature)}\` |`);
  }
  lines.push("", "Bold symbols are exported/public. Line numbers refer to the file at the revision above.");
  return lines.join("\n");
}

function escapeCell(value: string): string {
  return value.replace(/\|/g, "\\|").replace(/`/g, "'");
}
