// Phase 9I — renderer client for the native workspace-wide Tree-Sitter code map. Rust walks the
// workspace under the same skip rules as the search index, parses supported files with the
// compiled-in grammars and returns symbol metadata only (per file: kind, name, one-line signature,
// line range). No file contents cross this boundary; nothing is cached or written. The renderer
// turns the map into a compact, token-bounded markdown summary for Agent context.

import { invoke, isTauri } from "@tauri-apps/api/core";
import type { CodeOutlineSymbol } from "./codeOutline";

export const CODE_MAP_CONTEXT_PATH = "devlab-code-map.md";

export interface CodeMapRequest {
  prefix?: string;
  exportedOnly?: boolean;
}

export interface CodeMapFile {
  path: string;
  language: string;
  lineCount: number;
  size: number;
  symbolCount: number;
  truncated: boolean;
  hasSyntaxErrors: boolean;
  symbols: CodeOutlineSymbol[];
}

export interface CodeMapSkipped {
  ignoredDirectory: number;
  symlink: number;
  secretPattern: number;
  binaryExtension: number;
  unsupportedLanguage: number;
  tooLarge: number;
  notUtf8: number;
  unreadable: number;
  parseFailed: number;
  otherKind: number;
}

export interface CodeMapLimits {
  maxFiles: number;
  maxFileBytes: number;
  maxTotalBytes: number;
  maxTotalSymbols: number;
  maxSymbolsPerFile: number;
  maxDepth: number;
  buildDeadlineMs: number;
}

export interface CodeMapLanguageCount {
  language: string;
  files: number;
  symbols: number;
}

export interface CodeMap {
  prefix: string;
  exportedOnly: boolean;
  files: CodeMapFile[];
  fileCount: number;
  symbolCount: number;
  parsedBytes: number;
  skippedFiles: number;
  skippedDirectories: number;
  skipped: CodeMapSkipped;
  skippedSamples: string[];
  languages: CodeMapLanguageCount[];
  truncated: boolean;
  truncationReason: string | null;
  generatedAtMs: number;
  buildMs: number;
  limits: CodeMapLimits;
}

export function codeMapAdapterAvailable(): boolean {
  return isTauri();
}

export async function buildCodeMap(request: CodeMapRequest = {}): Promise<CodeMap> {
  const payload: CodeMapRequest = {};
  const prefix = (request.prefix ?? "").trim();
  if (prefix) payload.prefix = prefix;
  if (request.exportedOnly) payload.exportedOnly = true;
  return invoke<CodeMap>("code_map_build", { request: payload });
}

export function describeCodeMap(map: CodeMap): string {
  const parts = [
    `${map.symbolCount} symbol${map.symbolCount === 1 ? "" : "s"} across ${map.fileCount} file${map.fileCount === 1 ? "" : "s"}`,
    `${map.buildMs} ms`,
  ];
  if (map.exportedOnly) parts.push("exported only");
  if (map.prefix) parts.push(`under ${map.prefix}/`);
  if (map.truncated) parts.push(`truncated (${map.truncationReason ?? "budget"})`);
  return parts.join(" · ");
}

export interface RenderedCodeMap {
  markdown: string;
  renderedFiles: number;
  renderedSymbols: number;
  omittedFiles: number;
  clipped: boolean;
}

const KIND_ABBREVIATION: Record<string, string> = {
  function: "fn", method: "method", class: "class", interface: "interface", type: "type", enum: "enum",
  namespace: "namespace", module: "mod", struct: "struct", trait: "trait", impl: "impl", constant: "const",
  variable: "let", property: "prop", macro: "macro",
};

const MIN_RENDER_CHARS = 1_024;

/**
 * Renders the map as compact markdown within `maxChars`. Whole files are emitted in order until the
 * budget would be exceeded; the remainder is summarised as an omitted count rather than cut
 * mid-line, so the model never sees a dangling half-entry. Signatures are capped per line so one
 * long declaration cannot dominate the budget.
 */
export function renderCodeMap(map: CodeMap, maxChars: number): RenderedCodeMap {
  const budget = Math.max(MIN_RENDER_CHARS, Math.floor(maxChars));
  const header: string[] = [
    `# Workspace code map${map.prefix ? `: ${map.prefix}/` : ""}`,
    "Generated by DevLab's native Tree-Sitter code map (metadata only; no file contents).",
    `${map.fileCount} files · ${map.symbolCount} symbols · ${map.languages.map((entry) => `${entry.language} ${entry.files}f/${entry.symbols}s`).join(", ") || "no supported files"}${map.exportedOnly ? " · exported/public symbols only" : ""}`,
  ];
  if (map.truncated) header.push(`Note: the native build stopped early (${map.truncationReason ?? "budget"}); later files are missing.`);
  if (map.skippedFiles > 0) {
    header.push(`Skipped ${map.skippedFiles} files (${describeSkipped(map.skipped)}).`);
  }
  header.push("Legend: `kind name — signature (Lstart–end)`; `*` marks exported/public; indented entries are members.", "");

  // Reserve room for the worst-case omission footer so the final markdown never exceeds `budget`.
  const footerReserve = omissionFooter(map.files.length).length + 2;
  let used = header.join("\n").length + footerReserve;
  const body: string[] = [];
  let renderedFiles = 0;
  let renderedSymbols = 0;
  for (const file of map.files) {
    const block = renderFile(file);
    const size = block.join("\n").length + 1;
    if (used + size > budget) break;
    used += size;
    body.push(...block);
    renderedFiles += 1;
    renderedSymbols += file.symbols.length;
  }
  const omittedFiles = map.files.length - renderedFiles;
  const footer: string[] = [];
  if (omittedFiles > 0) {
    footer.push("", omissionFooter(omittedFiles));
  }
  const markdown = [...header, ...body, ...footer].join("\n");
  return { markdown, renderedFiles, renderedSymbols, omittedFiles, clipped: omittedFiles > 0 || map.truncated };
}

function omissionFooter(omittedFiles: number): string {
  return `… ${omittedFiles} more file${omittedFiles === 1 ? "" : "s"} omitted to stay within the context budget. Attach a per-file outline or narrow the prefix for detail.`;
}

function renderFile(file: CodeMapFile): string[] {
  const flags: string[] = [];
  if (file.hasSyntaxErrors) flags.push("syntax errors");
  if (file.truncated) flags.push("more symbols not shown");
  const lines = [`## ${file.path} (${file.language}, ${file.lineCount} lines${flags.length ? `; ${flags.join(", ")}` : ""})`];
  if (file.symbols.length === 0) {
    lines.push("- (no top-level symbols)");
    return lines;
  }
  for (const symbol of file.symbols) {
    const indent = symbol.depth > 0 ? "  " : "";
    const kind = KIND_ABBREVIATION[symbol.kind] ?? symbol.kind;
    const mark = symbol.exported ? "*" : "";
    const range = symbol.startLine === symbol.endLine ? `L${symbol.startLine}` : `L${symbol.startLine}–${symbol.endLine}`;
    const signature = clipSignature(symbol.signature, symbol.name);
    lines.push(`${indent}- ${kind} ${mark}${symbol.name} — \`${signature}\` (${range})`);
  }
  return lines;
}

const MAX_RENDERED_SIGNATURE = 110;

function clipSignature(signature: string, name: string): string {
  const cleaned = signature.replace(/`/g, "'").replace(/\s+/g, " ").trim();
  if (!cleaned) return name;
  if (cleaned.length <= MAX_RENDERED_SIGNATURE) return cleaned;
  return `${cleaned.slice(0, MAX_RENDERED_SIGNATURE - 1)}…`;
}

function describeSkipped(skipped: CodeMapSkipped): string {
  const entries: Array<[string, number]> = [
    ["unsupported language", skipped.unsupportedLanguage],
    ["secret-safe", skipped.secretPattern],
    ["binary", skipped.binaryExtension + skipped.notUtf8],
    ["too large", skipped.tooLarge],
    ["symlink", skipped.symlink],
    ["unreadable", skipped.unreadable],
    ["parse failed", skipped.parseFailed],
    ["other", skipped.otherKind],
  ];
  const described = entries.filter(([, count]) => count > 0).map(([label, count]) => `${count} ${label}`);
  return described.join(", ") || "none";
}
