// Phase 9L — renderer client for the native workspace dependency graph. Rust walks the workspace
// under the same skip rules as the search index, extracts each file's imports (no symbol parse, so
// it covers more files than the code map) and aggregates the resolved import edges into directory
// modules with weighted edges between them. No file contents cross this boundary; nothing is cached
// or written. The renderer turns the graph into a compact, token-bounded markdown summary that
// answers "how does this workspace fit together" for Agent context.

import { invoke, isTauri } from "@tauri-apps/api/core";

export const CODE_GRAPH_CONTEXT_PATH = "devlab-code-graph.md";

export interface CodeGraphRequest {
  prefix?: string;
}

export interface CodeGraphEdge {
  module: string;
  weight: number;
}

export interface CodeGraphModule {
  module: string;
  files: number;
  importance: number;
  internalEdges: number;
  externalDeps: number;
  externalSamples: string[];
  dependsOn: CodeGraphEdge[];
  dependedOnBy: CodeGraphEdge[];
}

export interface CodeGraphLimits {
  maxFiles: number;
  maxFileBytes: number;
  maxTotalBytes: number;
  maxModules: number;
  maxEdgesPerModule: number;
  buildDeadlineMs: number;
}

export interface CodeGraph {
  prefix: string;
  modules: CodeGraphModule[];
  moduleCount: number;
  omittedModules: number;
  fileCount: number;
  internalEdges: number;
  externalReferences: number;
  leafModules: number;
  truncated: boolean;
  truncationReason: string | null;
  skippedFiles: number;
  skippedDirectories: number;
  skippedSamples: string[];
  generatedAtMs: number;
  buildMs: number;
  limits: CodeGraphLimits;
}

export function codeGraphAdapterAvailable(): boolean {
  return isTauri();
}

export async function buildCodeGraph(request: CodeGraphRequest = {}): Promise<CodeGraph> {
  const payload: CodeGraphRequest = {};
  const prefix = (request.prefix ?? "").trim();
  if (prefix) payload.prefix = prefix;
  return invoke<CodeGraph>("code_graph_build", { request: payload });
}

export function describeCodeGraph(graph: CodeGraph): string {
  const parts = [
    `${graph.moduleCount} module${graph.moduleCount === 1 ? "" : "s"} / ${graph.fileCount} file${graph.fileCount === 1 ? "" : "s"}`,
    `${graph.internalEdges} import edge${graph.internalEdges === 1 ? "" : "s"}`,
    `${graph.buildMs} ms`,
  ];
  if (graph.externalReferences > 0) parts.push(`${graph.externalReferences} external`);
  if (graph.prefix) parts.push(`under ${graph.prefix}/`);
  if (graph.truncated) parts.push(`truncated (${graph.truncationReason ?? "budget"})`);
  return parts.join(" · ");
}

export interface RenderedCodeGraph {
  markdown: string;
  renderedModules: number;
  omittedModules: number;
  clipped: boolean;
}

const MIN_RENDER_CHARS = 1_024;

/**
 * Renders the graph as compact markdown within `maxChars`. Whole modules are emitted most-important
 * first until the budget would be exceeded; the remainder is summarised as an omitted count rather
 * than cut mid-module, so the model never sees a half edge list.
 */
export function renderCodeGraph(graph: CodeGraph, maxChars: number): RenderedCodeGraph {
  const budget = Math.max(MIN_RENDER_CHARS, Math.floor(maxChars));
  const header: string[] = [
    `# Workspace dependency graph${graph.prefix ? `: ${graph.prefix}/` : ""}`,
    "Generated by DevLab's native import graph (metadata only; no file contents).",
    `${graph.moduleCount} modules from ${graph.fileCount} files · ${graph.internalEdges} in-repo import edge${graph.internalEdges === 1 ? "" : "s"} · ${graph.externalReferences} external reference${graph.externalReferences === 1 ? "" : "s"} · ${graph.leafModules} stand-alone module${graph.leafModules === 1 ? "" : "s"}`,
    "Ordered by summed module importance (PageRank over in-repo imports); heaviest edges first.",
  ];
  if (graph.truncated) header.push(`Note: the native build stopped early (${graph.truncationReason ?? "budget"}); later modules are missing.`);
  if (graph.skippedFiles > 0) header.push(`Skipped ${graph.skippedFiles} unreadable or unsupported file${graph.skippedFiles === 1 ? "" : "s"}.`);
  header.push(
    "Legend: `module (files · importance×)`; `→` modules it imports with edge weight; `←` modules that import it; `ext:` packages outside the workspace.",
    "",
  );

  const footerReserve = omissionFooter(graph.moduleCount).length + 2;
  let used = header.join("\n").length + footerReserve;
  const body: string[] = [];
  let renderedModules = 0;
  for (const module of graph.modules) {
    const block = renderModule(module);
    const size = block.join("\n").length + 1;
    if (used + size > budget) break;
    used += size;
    body.push(...block);
    renderedModules += 1;
  }
  const omittedModules = graph.moduleCount - renderedModules;
  const footer: string[] = [];
  if (omittedModules > 0) {
    footer.push("", omissionFooter(omittedModules));
  }
  const markdown = [...header, ...body, ...footer].join("\n");
  return { markdown, renderedModules, omittedModules, clipped: omittedModules > 0 || graph.truncated };
}

function omissionFooter(omittedModules: number): string {
  return `… ${omittedModules} more module${omittedModules === 1 ? "" : "s"} omitted (least central first) to stay within the context budget. Narrow the workspace or attach a code map for detail.`;
}

function renderModule(module: CodeGraphModule): string[] {
  const flags: string[] = [];
  if (module.internalEdges > 0) flags.push(`${module.internalEdges} internal edge${module.internalEdges === 1 ? "" : "s"}`);
  const lines = [`## ${module.module} (${module.files} file${module.files === 1 ? "" : "s"} · ${module.importance.toFixed(2)}×${flags.length ? ` · ${flags.join(", ")}` : ""})`];
  if (module.dependsOn.length === 0) {
    lines.push("- → no cross-module dependencies");
  } else {
    lines.push(`- → ${module.dependsOn.map((edge) => `${edge.module} (${edge.weight})`).join(", ")}`);
  }
  if (module.dependedOnBy.length > 0) {
    lines.push(`- ← ${module.dependedOnBy.map((edge) => `${edge.module} (${edge.weight})`).join(", ")}`);
  }
  if (module.externalSamples.length > 0) {
    const shown = module.externalSamples.join(", ");
    const more = module.externalDeps - module.externalSamples.length;
    lines.push(`- ext: ${shown}${more > 0 ? ` +${more} more` : ""}`);
  }
  return lines;
}
