import { useState } from "react";
import { PanelHeader } from "./AgentPanel";
import { CodeBlock } from "../components/CodeBlock";
import { deployProviders } from "../data/runtimes";
import { loadDeploy, saveDeploy, type DeployConfig } from "../lib/settings";
import type { OpenGeneratedDrafts, VFile } from "../types";
import { Rocket, ExternalLink, KeyRound, CheckCircle2, Globe2, ShieldOff, FileDiff, Star } from "lucide-react";

/**
 * Non-secret, per-provider credential guidance. DevLab never asks for, stores or
 * exports these tokens: the CLI login runs in the user's own terminal and CI
 * secrets are configured in the CI provider.
 */
const credentialGuidance: Record<string, { envVar: string; login: string; note: string }> = {
  vercel: { envVar: "VERCEL_TOKEN", login: "vercel login", note: "Create a token under Account Settings → Tokens for CI use." },
  netlify: { envVar: "NETLIFY_AUTH_TOKEN", login: "netlify login", note: "Personal access tokens live under User settings → Applications." },
  render: { envVar: "RENDER_API_KEY", login: "render login", note: "Most Render deploys are Git-driven; the API key is only needed for the CLI or API." },
  railway: { envVar: "RAILWAY_TOKEN", login: "railway login", note: "Project tokens are scoped to one project/environment — prefer them over account tokens in CI." },
  fly: { envVar: "FLY_API_TOKEN", login: "fly auth login", note: "Use `fly tokens create deploy` for an app-scoped deploy token in CI." },
  cloudflare: { envVar: "CLOUDFLARE_API_TOKEN", login: "wrangler login", note: "Create an API token with the Workers/Pages edit template; account-wide keys are unnecessary." },
  supabase: { envVar: "SUPABASE_ACCESS_TOKEN", login: "supabase login", note: "Database pushes also need the project's database password, entered when the CLI prompts for it." },
  ghpages: { envVar: "GITHUB_TOKEN", login: "# no login: GitHub Actions injects GITHUB_TOKEN", note: "Grant the workflow `pages: write` and `id-token: write` permissions; no personal token is required." },
};

function workflowFor(providerId: string): { path: string; yaml: string } {
  const provider = deployProviders.find((p) => p.id === providerId) ?? deployProviders[0];
  const guidance = credentialGuidance[provider.id];
  const path = `.github/workflows/deploy-${provider.id}.yml`;
  if (provider.id === "ghpages") {
    return {
      path,
      yaml: `# Starting point generated by DevLab — review before committing. DevLab does not push workflows or read run status.
name: Deploy to GitHub Pages
on:
  push: { branches: [main] }
permissions:
  contents: read
  pages: write
  id-token: write
concurrency: { group: pages, cancel-in-progress: true }
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: { name: github-pages, url: \${{ steps.deployment.outputs.page_url }} }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: npm }
      - run: npm ci && npm run build
      - uses: actions/upload-pages-artifact@v3
        with: { path: dist }
      - id: deployment
        uses: actions/deploy-pages@v4`,
    };
  }
  const install = provider.cliInstall.split("\n")[0].replace(/^#.*$/, "").trim();
  const deploy = provider.deployCmd.split("\n")[0];
  return {
    path,
    yaml: `# Starting point generated by DevLab — review before committing. DevLab does not push workflows or read run status.
name: Deploy to ${provider.name}
on:
  push: { branches: [main] }
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: npm }
      - run: npm ci && npm run build
      - name: Deploy
        env:
          ${guidance.envVar}: \${{ secrets.${guidance.envVar} }}
        run: |
${install ? `          ${install}\n` : ""}          ${deploy}`,
  };
}

export function DeployPanel({ onOpenFiles }: { onOpenFiles?: OpenGeneratedDrafts }) {
  const [cfg, setCfg] = useState<DeployConfig>(loadDeploy);
  const [selected, setSelected] = useState(() => deployProviders.find((p) => p.id === loadDeploy().defaultProvider) ?? deployProviders[0]);
  const [notice, setNotice] = useState<{ kind: "ok" | "error"; text: string } | null>(null);
  const [staging, setStaging] = useState(false);

  const guidance = credentialGuidance[selected.id];
  const workflow = workflowFor(selected.id);
  const isDefault = cfg.defaultProvider === selected.id;

  function makeDefault() {
    const next: DeployConfig = { defaultProvider: selected.id };
    setCfg(next);
    saveDeploy(next);
    setNotice({ kind: "ok", text: `${selected.name} is now the default provider. Only this provider id is stored; no token is involved.` });
  }

  async function stageWorkflow() {
    if (!onOpenFiles || staging) return;
    setStaging(true);
    setNotice(null);
    try {
      const files: VFile[] = [{ path: workflow.path, content: `${workflow.yaml}\n`, language: "yaml" }];
      const opened = await onOpenFiles(files, `Deploy workflow starting point for ${selected.name}`);
      setNotice(opened
        ? { kind: "ok", text: `Staged ${workflow.path} for Editor review. Nothing is written until you apply it there, and committing or pushing it stays with you.` }
        : { kind: "error", text: "The workflow draft was not staged for editor review. Nothing was written." });
    } finally {
      setStaging(false);
    }
  }

  return (
    <div className="flex h-full flex-col">
      <PanelHeader
        title="Deployment"
        subtitle="Provider recipes and CI starting points — authoring only; DevLab does not deploy"
      />
      <div className="flex min-h-0 flex-1">
        <aside className="w-72 shrink-0 overflow-y-auto border-r border-white/5 bg-[#0d1017]/40 p-3">
          <div className="mb-2 px-1 text-[10.5px] font-semibold uppercase tracking-wider text-zinc-500">
            Providers
          </div>
          {deployProviders.map((p) => (
            <button
              key={p.id}
              onClick={() => { setSelected(p); setNotice(null); }}
              className={`mb-1 flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-left transition ${
                selected.id === p.id
                  ? "border border-cyan-500/30 bg-cyan-500/10"
                  : "border border-transparent hover:bg-white/5"
              }`}
            >
              <span
                className="h-6 w-6 shrink-0 rounded-md ring-1 ring-white/10"
                style={{ background: `linear-gradient(135deg, ${p.color}40, ${p.color}10)` }}
              />
              <div className="min-w-0 flex-1">
                <div className="truncate text-[13px] font-medium text-zinc-100">{p.name}</div>
                <div className="truncate text-[11px] text-zinc-500">{p.freeTier}</div>
              </div>
              {cfg.defaultProvider === p.id && <Star className="h-3.5 w-3.5 shrink-0 text-amber-300" aria-label="Default provider" />}
            </button>
          ))}
          <p className="mt-3 px-1 text-[10.5px] leading-relaxed text-zinc-500">
            The default provider id is the only deployment setting DevLab stores. No tokens are saved anywhere.
          </p>
        </aside>

        <div className="flex-1 overflow-y-auto p-7">
          <div className="flex items-start gap-4">
            <div
              className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl ring-1 ring-white/10"
              style={{ background: `linear-gradient(135deg, ${selected.color}35, ${selected.color}10)` }}
            >
              <Rocket className="h-6 w-6" style={{ color: selected.color }} />
            </div>
            <div className="flex-1">
              <h2 className="text-2xl font-semibold text-white">{selected.name}</h2>
              <p className="mt-1 text-sm text-zinc-400">{selected.tagline}</p>
              <div className="mt-2 inline-flex items-center gap-1.5 rounded-md bg-emerald-500/10 px-2 py-0.5 text-[11.5px] text-emerald-300 ring-1 ring-emerald-500/20">
                <CheckCircle2 className="h-3 w-3" /> Free tier: {selected.freeTier}
              </div>
            </div>
            <div className="flex shrink-0 items-center gap-2">
              <button
                onClick={makeDefault}
                disabled={isDefault}
                className="inline-flex items-center gap-1.5 rounded-lg border border-white/10 px-3 py-1.5 text-xs text-zinc-300 hover:bg-white/5 disabled:opacity-50"
              >
                <Star className="h-3 w-3" /> {isDefault ? "Default provider" : "Make default"}
              </button>
              <a
                href={selected.docs} target="_blank" rel="noreferrer"
                className="inline-flex items-center gap-1.5 rounded-lg border border-white/10 px-3 py-1.5 text-xs text-zinc-300 hover:bg-white/5"
              >
                Docs <ExternalLink className="h-3 w-3" />
              </a>
            </div>
          </div>

          <div className="mt-5 flex flex-wrap gap-1.5">
            {selected.supports.map((s) => (
              <span key={s} className="rounded-md bg-white/5 px-2 py-0.5 text-[11px] text-zinc-400">{s}</span>
            ))}
          </div>

          <div className="mt-6 flex items-start gap-2.5 rounded-xl border border-amber-500/20 bg-amber-500/[0.05] p-4 text-[13px] text-amber-100/90">
            <ShieldOff className="mt-0.5 h-4 w-4 shrink-0 text-amber-300" />
            <span>
              <strong>Native deployment is disabled.</strong> DevLab does not run deployment commands, does not store
              deployment tokens and never edits your shell profile. Everything below is a recipe: run the commands in the
              integrated terminal or your own shell, and authenticate with the provider CLI there. Deployment automation is
              deferred until bounded, audited and confirmation-gated command execution exists.
            </span>
          </div>

          <section className="mt-7 rounded-xl border border-white/10 bg-white/[0.02] p-5 ring-soft">
            <div className="mb-3 flex items-center gap-2.5">
              <KeyRound className="h-4 w-4 text-cyan-300" />
              <h3 className="text-sm font-semibold text-white">{selected.tokenLabel}</h3>
            </div>
            <p className="text-[12.5px] leading-relaxed text-zinc-400">
              DevLab has no protected storage for deployment credentials yet, so it does not ask for this token. Log in with the
              CLI in your terminal for interactive use, and put the token in your CI provider's secret store as{" "}
              <code className="rounded bg-black/30 px-1 font-mono text-[11.5px] text-cyan-200">{guidance.envVar}</code> for
              non-interactive deploys. {guidance.note}
            </p>
            <div className="mt-3">
              <CodeBlock code={guidance.login} lang="bash" />
            </div>
          </section>

          <h3 className="mb-2 mt-7 text-sm font-semibold text-white">1 · Install the CLI</h3>
          <CodeBlock code={selected.cliInstall} lang="bash" />

          <h3 className="mb-2 mt-5 text-sm font-semibold text-white">2 · Deploy from your terminal</h3>
          <CodeBlock code={selected.deployCmd} lang="bash" />

          <div className="mb-2 mt-5 flex items-center justify-between gap-3">
            <h3 className="text-sm font-semibold text-white">3 · CI workflow starting point</h3>
            {onOpenFiles && (
              <button
                onClick={() => { void stageWorkflow(); }}
                disabled={staging}
                className="inline-flex items-center gap-1.5 rounded-lg border border-cyan-400/25 px-3 py-1.5 text-xs font-semibold text-cyan-100 hover:bg-cyan-400/10 disabled:opacity-50"
              >
                <FileDiff className="h-3.5 w-3.5" /> Stage {workflow.path} for review
              </button>
            )}
          </div>
          <CodeBlock lang="yaml" code={workflow.yaml} />
          <p className="mt-2 text-[11.5px] leading-relaxed text-zinc-500">
            Staging uses the same reviewed-draft gate as Project Builder (path policy, Rust metadata validation, explicit
            per-file Apply in the Editor). Committing and pushing the workflow, adding the{" "}
            <span className="font-mono">{guidance.envVar}</span> secret and watching the run all happen in Git and your CI
            provider — DevLab does not push workflows or read run status.
          </p>

          {notice && (
            <div className={`mt-4 rounded-lg border px-3 py-2 text-[12px] ${notice.kind === "ok" ? "border-emerald-500/25 bg-emerald-500/[0.06] text-emerald-200" : "border-amber-500/25 bg-amber-500/[0.06] text-amber-200"}`}>
              {notice.text}
            </div>
          )}

          <div className="mt-6 flex items-start gap-2.5 rounded-xl border border-cyan-500/20 bg-cyan-500/[0.05] p-4 text-[13px] text-cyan-100/90">
            <Globe2 className="mt-0.5 h-4 w-4 shrink-0" />
            <span>
              The integrated terminal in the desktop build is a real PTY, so the provider CLI's own login and deploy flows
              work there exactly as in any shell — DevLab just does not start them for you.
            </span>
          </div>
        </div>
      </div>
    </div>
  );
}
